### ISSUE TITLE
Query Messaging Unread Count

### ISSUE THREAD

**Issue by f2m2rd** [smilefam/jiver-ios-framework#1]
Hello,

The `queryMessagingUnreadCount` method  always seems to return Zero (0).   Can you please verify that it is working?

```
let count = Jiver.queryMessagingUnreadCount()

count.executeWithResultBlock({ (count) -> Void in	
	println("count: \(count)") // NOTE, THIS ALWAYS RETURNS ZERO (0)
				
}, errorBlock: { (errorCode) -> Void in
	
	println("error: \(errorCode)")

})```

**Comment by sf-jed-kyung** [comment]
Thank you for using this framework.

`queryMessagingUnreadCount` returns the sum of unread counts of `JiverMessagingChannel`.

Please check whether you created `JiverMessagingChannel` or `JiverChannel`.

**Comment by f2m2rd** [comment]
Ah, so it doesn't work with a `JiverChannel`.

Do you know if a way to get an unread message count for a particular user within a `JiverChannel`?

**Comment by sf-jed-kyung** [comment]
`JiverChannel` doesn’t provide an unread message count. If you want to get it, you should create `JiverMessagingChannel`.

**Comment by f2m2rd** [comment]
Thanks. Unless I'm misunderstanding the documentation, The `JiverMessagingChannel` does not seem to be a good fit for our application.  We need the ability for the same group of users to chat in different channels.
