### ISSUE TITLE
Push Callback

### ISSUE THREAD

**Issue by f2m2rd** [smilefam/jiver-ios-framework#2]
Does push callback work? 
https://jiver.gitbooks.io/ios-sdk/content/en/push_callback.html

We receive only test JSON data from the webhook.

**Comment by sf-jed-kyung** [comment]
Push callback works on `JiverMessagingChannel`. Are you sure that you are in `JiverMessagingChannel`? If there are offline users in `JiverMessagingChannel` and some online users write messages in the channel, your callback server will receive the messages.

**Comment by f2m2rd** [comment]
Thanks for the reply @sf-jed-kyung 

So your saying that this doesn't work with JiverChannel?  Can you update the docs to reflect this?

Any plans on making this work for push notifications?

**Comment by f2m2rd** [comment]
Also, is it possible that we can set up a call with someone from your team?  We have this service up and running for our app and before we go live, we want to make sure this will work for our needs.

**Comment by sf-jed-kyung** [comment]
Sorry about that. I should update the documents for removing misunderstanding. JIVER CEO John. Kim(john@jiver.io) sent an e-mail about your requirements. Please check your inbox.
